### ISSUE TITLE
Tag v1.3.4 release

### ISSUE THREAD

**Issue by rillian** [xiph/ogg#55]
@tmatth asked me to make a new release. I'm slowly going through the accumulated PRs and issues to get things ready to go.

If you haven't tested the ogg development tree recently, now is a good time!

**Comment by willson-chen** [comment]
looking forward the new release!

**Comment by rillian** [comment]
NB there are a number of bug reports and patches in the [upstream gitlab repo](https://gitlab.xiph.org/xiph/ogg/issues). I'm also going through those. Help sorting and reviewing appreciated!

**Comment by rillian** [comment]
I'm away next week, but will publish a release the week after that.

**Comment by rillian** [comment]
Release is tagged and source packages are posted!
