### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mgeier** [xiph/ogg#71]
When is the next `libogg` release planned?

The latest release of `libFLAC` (1.3.3) seems to be incompatible to the latest release of `libogg` (1.3.4).
The problem apparently has been fixed in the `master` branch (see also https://gitlab.xiph.org/xiph/ogg/-/issues/1747).

**Comment by ericoporto** [comment]
can we have a new release of this, the current release is broken -> https://trac.macports.org/ticket/58924

**Comment by rillian** [comment]
I've publish a `libogg-1.3.5` release based on the current tree. Please report any new issues!

**Comment by mgeier** [comment]
Thanks @rillian, no issues so far!
