### ISSUE TITLE
ogg.m4 is useless

### ISSUE THREAD

**Issue by vtorri** [xiph/ogg#88]
everything in the title

**Comment by ktmf01** [comment]
It seems you have a problem with ogg.m4. If you want it fixed, please explain what your problem is.

For my own use case, ogg.m4 works fine, so at the very least you could explain your use case.

**Comment by vtorri** [comment]
hello

i didn't say that there is a problem with ogg.m4, i just said it is useless
:

 * the m4 macro is not used in configure.ac
 * ogg.pc is used to check for libogg existence

so ogg.m4 is useless

Vincent Torri

**Comment by rillian** [comment]
ogg.m4 is included in the ogg repository for the convenience of projects using the library. If they prefer m4 detection over pkg-config, this acts as a source for the `XIPH_PATH_OGG` macro.
