### ISSUE TITLE
Gitlab down?

### ISSUE THREAD

**Issue by Baklap4** [xiph/ogg#92]
VCPKG is using the gitlab instance to download the latest version. However gitlab returns a 500 see: https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz

VCPKG ticket: https://github.com/microsoft/vcpkg/issues/31930
https://github.com/microsoft/vcpkg/issues/31927

**Comment by Baklap4** [comment]
Can be closed, gitlab returns the files again, thanks

**Comment by ohmaseclaro** [comment]
once again this is offline!
